[server]
maxUploadSize = 400
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[global]
disableWatchdogWarning = true

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"