[server]
enableStaticServing = true
enableCORS = false
maxUploadSize = 400

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false

[theme]
base="dark"
primaryColor="#2563eb"
backgroundColor="#0a192f"
secondaryBackgroundColor="#1e293b"
textColor="#f8fafc"